// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Victor.Movies.DataAccess.Models;
using Victor.Movies.DataAccess.Data.Mappings;

namespace Victor.Movies.DataAccess.Data.Context;

public partial class MoviesDbContext : DbContext
{
    public MoviesDbContext(DbContextOptions<MoviesDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Diretor> Diretors { get; set; }

    public virtual DbSet<Filme> Filmes { get; set; }

    public virtual DbSet<Genero> Generos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new DiretorMap());
        modelBuilder.ApplyConfiguration(new FilmeMap());
        modelBuilder.ApplyConfiguration(new GeneroMap());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}