// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Victor.Movies.DataAccess.Models;

public partial class Diretor
{
    public int Id { get; set; }

    public string Nome { get; set; }

}