// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Victor.Movies.DataAccess.Models;

public partial class Genero
{
    public int GenderId { get; set; }

    public string Gender { get; set; }
}